name: deploy whoisdg

on:
    push:
        branches:
            - main

jobs:
    push-to-docker:
        runs-on: ubuntu-latest
        steps:
            - name: login to docker
              env:
                DOCKER_USER: ${{ secrets.DOCKER_USER }}
                DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
              run:
                docker login -u $DOCKER_USER -p $DOCKER_PASS
            - name: push image to docker
              env:
                REPO: whoisdg
              run: |
                docker build -t $DOCKER_USER/$REPO .
                docker push $DOCKER_USER/$REPO

    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: ${{ env.AWS_REGION }}

            - name: ssh to EC2 to deploy
              env:
                DOCKER_USER: ${{ secrets.DOCKER_USER }}
                REPO: whoisdg
                PORT: ${{ env.HOST_PORT }}
              uses: appleboy/ssh-action@master
              with:
                host: ${{ secrets.HOST }}
                username: ${{ secrets.EC2_USERNAME }}
                key: ${{ secrets.SSH_KEY }}
                script: |
                    docker pull $DOCKER_USER/$REPO
                    docker run --rm --name $REPO -p $PORT:$PORT -d $DOCKER_USER/$REPO
              

