name: Docker Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Build and Push Docker Image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASS }}
        run: |
          echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin
          docker build -t $DOCKER_USERNAME/whoisdg .
          docker push $DOCKER_USERNAME/whoisdg

      - name: SSH into EC2 and Deploy Docker Image
        uses: appleboy/ssh-action@master
        env:
            PORT: ${{ secrets.APPLICATION_PORT }}
            DOCKER_USER: ${{ secrets.DOCKER_USER }}
        with:
          host: ${{ secrets.HOST_IP }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker stop whoisdg || true
            docker rm whoisdg || true
            docker pull $DOCKER_USER/whoisdg
            docker run -d --rm --name whoisdg -p $PORT:$PORT $DOCKER_USER/whoisdg
