name: Deploy to Server

on:
  workflow_run:
    workflows: ["Build and Push to DockerHub"]
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy-to-server:
    runs-on: ubuntu-latest
    steps:
      - name: deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_IP }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker pull dgclasher/whoisdg
            docker stop whoisdg || true
            docker run -d --rm --name whoisdg --env-file ${{ secrets.ENV_FILE }} -p 80:${{ secrets.APPLICATION_PORT }}  dgclasher/whoisdg
