name: deploy whoisdg

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      
      - name: checkout code
        uses: actions/checkout@v2

      - name: login to dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKET_USER}}
          password: ${{secrets.DOCKER_PASS}}
      - name: build and push docket image
        uses: docket/build-push-action@v2
        with:
          context: .
          push: true
          tags: dgclasher/whoisdg

      - name: deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_IP }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker stop whoisdg || true
            docker rm whoisdg || true
            docker pull ${{secrets.DOCKER_USER}}/whoisdg
            docker run -d --rm --name whoisdg -p ${{secrets.APPLICATION_PORT}}:${{secrets.APPLICATION_PORT}}  ${{secrets.DOCKER_USER}}/whoisdg
