name: deploy to server
on:
  # workflow_run:
  #   workflows: ["build and push to docker"]
  #   types:
  #     - completed
  workflow_dispatch:
jobs:
  deploy-to-server:
    runs-on: ubuntu-latest
    steps:
      - name: deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_IP }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USER }}/whoisdg
            docker stop whoisdg || true
            docker run -d --rm --name whoisdg --env-file ${{ secrets.ENV_FILE }} -p 80:${{ secrets.APPLICATION_PORT }}  ${{ secrets.DOCKER_USER }}/whoisdg
